### ISSUE TITLE
block length and DataFrame

### ISSUE THREAD

**Issue by tbeason** [colintbowers/DependentBootstrap.jl#7]
When I supply a `Tx2` `DataFrame` and a block length `x` to `dbootdata`, the actual block length that gets used is `x/2`. Is this expected?

(It was not expected by me!)

**Comment by colintbowers** [comment]
Definitely not expected. I'll try to reproduce this tonight. In the meantime, is it only `DataFrame` where this happens? If you input a `Matrix` instead do you get the same behaviour? (if not that should make it *very* easy to work out where the problem is).

**Comment by colintbowers** [comment]
Also, could you tell me what the value of `x` is relative to `T`? It's possible your block length is being truncated because it is infeasibly large.

**Comment by colintbowers** [comment]
I can't reproduce this. Is there any chance you could post an MWE (minimum working example)? At the very least, if you could paste the call to `dbootdata` you are using, indicating the values of all keyword arguments if you're using the keyword method. If you're using the `BootInput` method, then please just paste the output of `show(bi)` where `bi` is your `BootInput` (that will tell me everything I need to know). Also, just to be certain we're on the same page, could you post the version number you're using? (use `]` to enter package environment, and then `status`)

**Comment by tbeason** [comment]
Silly me. I was using the wrong kind of bootstrapping method. I had input stationary when I wanted circular. I believe stationary changes the block size. Circular works fine and gives me correct blocks.

**Comment by colintbowers** [comment]
Yes that'd be it. Stationary has a stochastic block length using a
geometric distribution, so the block length will be on average equal to the
input block length, but sometimes smaller, and sometimes larger.
